language: cpp

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

dist: trusty

notifications:
  email: false
 
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
   - os: linux
     compiler: gcc
     addons:
       apt:
         sources:
           - ubuntu-toolchain-r-test
         packages:
           - g++-6
     env:
       - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
   - os: linux
     compiler: clang
     addons:
       apt:
         sources:
           - ubuntu-toolchain-r-test
           - llvm-toolchain-precise-3.7
         packages:
           - clang-3.6
     env:
       - MATRIX_EVAL="CC=clang-3.6 && CXX=clang++-3.6"
before_install:
  - eval "${MATRIX_EVAL}"
  - make
script: 
  - make install
