language: cpp

os:
  - linux
  - osx

dist: trusty

notifications:
  email: false

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - eval "${MATRIX_EVAL}"

install: true

script:
  - make
