language: cpp

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

dist: trusty

notifications:
  email: false
 
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
before_install:
  - eval "${MATRIX_EVAL}"
  - make
script: 
  - make install
